{{- define "deployment.app" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    manager: ahoy
    app: {{ .app.name }}
    releaseName: {{ .glob.releaseName }}
    environment: {{ .glob.environment }}
  name: {{ .glob.releaseName }}-{{ .app.name }}
spec:
  replicas: {{ .app.replicas }}
  selector:
    matchLabels:
      manager: ahoy
      app: {{ .app.name }}
      releaseName: {{ .glob.releaseName }}
      environment: {{ .glob.environment }}
  template:
    metadata:
      labels:
        manager: ahoy
        app: {{ .app.name }}
        releaseName: {{ .glob.releaseName }}
        environment: {{ .glob.environment }}
    spec:
      {{ if .app.dockerConfigJson }}
      imagePullSecrets:
        - name: {{ .glob.releaseName }}-{{ .app.name }}
      {{ end }}
      containers:
        - image: {{ .app.image }}
          imagePullPolicy: Always
          name: {{ .glob.releaseName }}-{{ .app.name }}
          {{ if .app.environmentVariables }}
          env:
            {{- range $name, $envVariable := .app.environmentVariables }}
            {{ if eq $envVariable.type "Value"}}
            - name: {{ $name }}
              value: '{{ $envVariable.value }}'
            {{ end }}
            {{ if eq $envVariable.type "Secret"}}
            - name: {{ $name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.glob.releaseName }}-{{ $.app.name }}-{{ $envVariable.secretName }}
                  key: {{ $envVariable.secretKey }}
            {{ end }}
            {{- end }}
          {{ end }}
          {{ if .app.servicePorts }}
          ports:
            {{- range .app.servicePorts }}
            - containerPort: {{ . }}
              protocol: TCP
            {{- end }}
          {{ end }}
          {{ if and .app.healthEndpointPath .app.healthEndpointPort .app.healthEndpointScheme }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: {{ .app.healthEndpointPath }}
              port: {{ .app.healthEndpointPort }}
              scheme: {{ .app.healthEndpointScheme }}
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: {{ .app.healthEndpointPath }}
              port: {{ .app.healthEndpointPort }}
              scheme: {{ .app.healthEndpointScheme }}
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          {{ end }}
          resources: {}
          {{ if or .app.configs .app.volumes }}
          volumeMounts:
            {{ if .app.configs}}
            - name: application-config
              mountPath: {{ .app.configPath }}
            {{ end }}
            {{- range $name, $volume := .app.volumes }}
            - name: {{ $volume.name }}
              mountPath: {{ $volume.mountPath }}
            {{- end }}
          {{ end }}
      {{ if or .app.configs .app.volumes}}
      volumes:
        {{ if .app.configs}}
        - name: application-config
          configMap:
            name: {{ .glob.releaseName }}-{{ .app.name }}
        {{ end }}
        {{- range $name, $volume := .app.volumes }}
        - name: {{ $volume.name }}
          {{ if eq $volume.type "PersistentVolume"}}
          persistentVolumeClaim:
            claimName: {{ $.glob.releaseName }}-{{ $.app.name }}-{{ $volume.name }}
          {{ end }}
          {{ if eq $volume.type "Secret"}}
          secret:
            secretName: {{ $.glob.releaseName }}-{{ $.app.name }}-{{ $volume.secretName }}
          {{ end }}
        {{- end}}
      {{ end }}
  {{- end -}}
