{{- define "deployment.app" -}}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    manager: ahoy
    app: {{ .glob.releaseName }}
    releaseName: {{ .glob.releaseName }}
    environment: {{ .glob.environment }}
  name: {{ .glob.releaseName }}-{{ .app.name }}
spec:
  replicas: {{ .app.replicas }}
  template:
    metadata:
      labels:
        manager: ahoy
        app: {{ .app.name }}
        releaseName: {{ .glob.releaseName }}
        environment: {{ .glob.environment }}
    spec:
      containers:
        - image: {{ .glob.dockerRegistry }}/{{ .glob.imageNamespace }}/{{ .glob.releaseName }}-{{ .app.name }}:{{ .app.version }}
          imagePullPolicy: Always
          name: {{ .glob.releaseName }}-{{ .app.name }}
          {{ if .app.environmentVariables }}
          env:
            {{- range $name, $value := .app.environmentVariables }}
            - name: {{ $name }}
              value: '{{ $value }}'
            {{- end }}
          {{ end }}
          {{ if .app.servicePorts }}
          ports:
            {{- range .app.servicePorts }}
            - containerPort: {{ . }}
              protocol: TCP
            {{- end }}
          {{ end }}
          {{ if and .app.healthEndpointPath .app.healthEndpointPort .app.healthEndpointScheme }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: {{ .app.healthEndpointPath }}
              port: {{ .app.healthEndpointPort }}
              scheme: {{ .app.healthEndpointScheme }}
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: {{ .app.healthEndpointPath }}
              port: {{ .app.healthEndpointPort }}
              scheme: {{ .app.healthEndpointScheme }}
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          {{ end }}
          resources: {}
          {{ if and .app.configs .app.configPath }}
          volumeMounts:
            - name: application-config
              mountPath: {{ .app.configPath }}
          {{ end }}
      {{ if and .app.configs .app.configPath }}
      volumes:
        - name: application-config
          configMap:
            name: {{ .glob.releaseName }}-{{ .app.name }}
      {{ end }}
  {{- end -}}
