{{- define "imagestream.app" -}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    manager: ahoy
    app: {{ .app.name }}
    releaseName: {{ .glob.releaseName }}
    environment: {{ .glob.environment }}
  name: {{ .glob.releaseName }}-{{ .app.name }}
  namespace: {{ .glob.imageNamespace }}
spec:
  tags:
    - from:
        kind: DockerImage
        name: {{ .app.image }}
      name: "{{ .app.version }}"
      referencePolicy:
        type: Local
  {{- end -}}
