{{- define "ingress.app" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    manager: ahoy
    app: {{ .app.name }}
    releaseName: {{ .glob.releaseName }}
    environment: {{ .glob.environment }}
  name: {{ .glob.releaseName }}-{{ .app.name }}
spec:
  {{- if .app.tls }}
  tls:
  - hosts:
      - {{ .app.routeHostname }}
    secretName: {{ .glob.releaseName }}-{{ .app.name }}-{{ .app.tlsSecretName }}
  {{- end }}
  rules:
  - host: {{ .app.routeHostname }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .glob.releaseName }}-{{ .app.name }}
              port:
                number: {{ .app.routeTargetPort }}
{{- end -}}
