{{- define "secret-dockerconfig.app" -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    manager: ahoy
    app: {{ .app.name }}
    releaseName: {{ .glob.releaseName }}
    environment: {{ .glob.environment }}
  name: {{ .glob.releaseName }}-{{ .app.name }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    .dockerconfigjson: {{ .app.dockerConfigJson }}
  template:
    type: kubernetes.io/dockerconfigjson
    metadata:
      labels:
        manager: ahoy
        app: {{ .app.name }}
        releaseName: {{ .glob.releaseName }}
        environment: {{ .glob.environment }}
      name: {{ .glob.releaseName }}-{{ .app.name }}
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
  {{- end -}}
