{{- define "configmap.app" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    manager: ahoy
    app: {{ .app.name }}
    releaseName: {{ .glob.releaseName }}
    environment: {{ .glob.environment }}
  name: {{ .glob.releaseName }}-{{ .app.name }}
data:
  {{- range .app.configs }}
  {{ .name }}: |-
    {{ .config }}
  {{- end }}
{{- end -}}
